Task 1: Load the dataset, check for missing values and duplicates, impute missing numerical columns using the appropriate measure of central tendency based on skewness, and remove duplicate rows.

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [30]:
# Loading Dataset.
df = pd.read_csv("cardekho_dataset.csv")
df.head()

   Unnamed: 0       car_name    brand  ... max_power  seats  selling_price
0           0    Maruti Alto   Maruti  ...     46.30      5         120000
1           1  Hyundai Grand  Hyundai  ...     82.00      5         550000
2           2    Hyundai i20  Hyundai  ...     80.00      5         215000
3           3    Maruti Alto   Maruti  ...     67.10      5         226000
4           4  Ford Ecosport     Ford  ...     98.59      5         570000

[5 rows x 14 columns]

In [31]:
# checking for missing values
df.isna().sum()/len(df) * 100

Unnamed: 0           0.0
car_name             0.0
brand                0.0
model                0.0
vehicle_age          0.0
km_driven            0.0
seller_type          0.0
fuel_type            0.0
transmission_type    0.0
mileage              0.0
engine               0.0
max_power            0.0
seats                0.0
selling_price        0.0
dtype: float64

In [32]:
# chaeking duplicates values
df.duplicated().sum()

np.int64(0)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [34]:
# Dropping the unwanted columns
df = df.drop(columns=['Unnamed: 0', "car_name", "model"])

In [35]:
print(f"Shape of the dataset: {df.shape}")
print(f"{df.info()}")

Shape of the dataset: (15411, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              15411 non-null  object
 1   vehicle_age        15411 non-null  int64
 2   km_driven          15411 non-null  int64
 3   seller_type        15411 non-null  object
 4   fuel_type          15411 non-null  object
 5   transmission_type  15411 non-null  object
 6   mileage            15411 non-null  float64
 7   engine             15411 non-null  int64
 8   max_power          15411 non-null  float64
 9   seats              15411 non-null  int64
 10  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(4)
memory usage: 1.3+ MB
None

Task 2: Apply one-hot encoding to any categorical column in the dataset, split the data into training and test sets (80/20), and then scale the numerical features using StandardScaler — ensuring scaling is applied after the split.

In [36]:
# Apply one-hot encoding to any categorical column in the dataset
print(df['seller_type'].value_counts())
print(df['seller_type'].unique())

seller_type
Dealer              9539
Individual          5699
Trustmark Dealer     173
Name: count, dtype: int64
['Individual' 'Dealer' 'Trustmark Dealer']

In [37]:
print(df['fuel_type'].value_counts())
print(df['fuel_type'].unique())

fuel_type
Petrol      7643
Diesel      7419
CNG          301
LPG           44
Electric       4
Name: count, dtype: int64
['Petrol' 'Diesel' 'CNG' 'LPG' 'Electric']

In [38]:
print(df['transmission_type'].value_counts())
print("\n",df['transmission_type'].unique())

transmission_type
Manual       12225
Automatic     3186
Name: count, dtype: int64

 ['Manual' 'Automatic']

In [39]:
print(df['brand'].value_counts())
print(df['brand'].unique())

brand
Maruti           4992
Hyundai          2982
Honda            1485
Mahindra         1011
Toyota            793
Ford              790
Volkswagen        620
Renault           536
BMW               439
Tata              430
Mercedes-Benz     337
Skoda             334
Audi              192
Datsun            170
Jaguar             59
Land Rover         51
Jeep               41
Kia                32
Porsche            21
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
Maserati            2
ISUZU               2
Ferrari             1
Mercedes-AMG        1
Rolls-Royce         1
Force               1
Name: count, dtype: int64
['Maruti' 'Hyundai' 'Ford' 'Renault' 'Mini' 'Mercedes-Benz' 'Toyota'
 'Volkswagen' 'Honda' 'Mahindra' 'Datsun' 'Tata' 'Kia' 'BMW' 'Audi'
 'Land Rover' 'Jaguar' 'MG' 'Isuzu' 'Porsche' 'Skoda' 'Volvo' 'Lexus'
 'Jeep' 'Maserati' 'Bentley' 'Nissan' 'ISUZU' 'Ferrari' 'Mercedes-AMG'
 'Rolls-Royce' 'Force']

In [40]:
print(f"Before Encoding: {df.shape}")
df = pd.get_dummies(df,columns=['transmission_type'])
print(f"After Encoding: {df.shape}")

Before Encoding: (15411, 11)
After Encoding: (15411, 12)

In [41]:
print(f"Before Encoding: {df.shape}")
df = pd.get_dummies(df, columns=['seller_type', 'fuel_type', 'brand'], drop_first=True)
print(f"After Encoding: {df.shape}")

Before Encoding: (15411, 12)
After Encoding: (15411, 46)

In [ ]:
# split the data into training and test sets (80/20)
x = df.drop(columns='selling_price')
y = df['selling_price']

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.80, random_state= 42)

print(f"Train: {x_train.shape[0]} rows ({x_train.shape[0]/len(x)*100:.0f}%)")
print(f"Test:  {x_test.shape[0]} rows ({x_test.shape[0]/len(x)*100:.0f}%)")

Train: 12328 rows (80%)
Test:  3083 rows (20%)

In [44]:
scaler = StandardScaler()
numeric_cols = ['vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power', 'seats']
x_train[numeric_cols] = scaler.fit_transform(x_train[numeric_cols])
x_train

       vehicle_age  km_driven  ...  brand_Volkswagen  brand_Volvo
11210     0.323969   0.349100  ...             False         True
1347     -1.337798  -1.069394  ...             False        False
10363    -1.337798  -1.163564  ...             False        False
316       0.323969   0.178369  ...             False        False
10638     1.321030   0.585469  ...             False        False
...            ...        ...  ...               ...          ...
5191      0.323969   1.702310  ...             False        False
13418     1.653383   0.084198  ...              True        False
5390      0.323969  -0.833967  ...             False        False
860      -1.337798  -0.951680  ...             False        False
7270     -1.337798  -0.598540  ...             False        False

[12328 rows x 45 columns]