Task 1 — Load, Inspect, and Clean

In [67]:
# Download the Dataset:
import pandas as pd
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("manishkr1754/cardekho-used-car-data")

# print("Path to dataset files:", path)

In [68]:
df = pd.read_csv("used_cars_messy.csv")
df.head(5)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0

In [69]:
# drop column
df = df.drop(columns='Unnamed: 0')

Perform the following:

Print df.shape, df.info(), and df.isnull().sum() * 100 / len(df).

Drop rows where selling_price is missing.

For columns mileage, engine, and max_power — strip any unit strings (e.g. "kmpl", "CC", "bhp"), convert to numeric using pd.to_numeric(..., errors='coerce'), and fill remaining nulls with each column's median.

Remove rows where selling_price is 999999999 or below 10000.

Drop all duplicate rows.

Print df.shape again after cleaning.

In [70]:
# Shape of Dataset
df.shape

(15661, 13)

In [71]:
# Chacking the how many columns and Datatypes of Dataset.  
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15661 non-null  object
 1   brand              15661 non-null  object
 2   model              15661 non-null  object
 3   vehicle_age        15661 non-null  int64
 4   km_driven          15661 non-null  object
 5   seller_type        15661 non-null  object
 6   fuel_type          15661 non-null  object
 7   transmission_type  15661 non-null  object
 8   mileage            14376 non-null  object
 9   engine             13792 non-null  float64
 10  max_power          14862 non-null  float64
 11  seats              15218 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.6+ MB

In [72]:
# Cheaking null values Percentage. in Dataset.  
df.isna().sum() *100 /len(df)

car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

In [73]:
# Drop rows where selling_price is missing.

df = df.dropna(subset=['selling_price'])
df['selling_price'].isna().sum() *100 /len(df)

np.float64(0.0)

In [74]:
df['engine'].unique()

array([1461.,  998., 1497., 2179., 1197.,   nan, 1498., 1248., 1956.,
       1399., 1298., 1582., 1396.,  796., 1997., 1196., 1598., 1199.,
       1462., 1991., 1493.,  799., 1198., 1796., 2523.,  999., 1995.,
       1968., 2143., 2987., 1120., 1499., 1373., 2487., 1086., 2494.,
       2993., 1999., 3198., 1591., 2497., 2393., 1496., 2755., 1950.,
       1186., 1798., 2997., 2982., 2967., 1368., 4134., 1047., 1599.,
       1998., 2694., 4367., 1799., 2498., 1194.,  793., 1984., 2092.,
       1061., 2199., 2499., 2148., 1896., 1797., 2998., 3498., 2354.,
       3456., 1781., 1353., 2996., 1343., 2698., 2999., 3628., 2609.,
       2979., 2362., 5461., 1451., 2157., 1969., 3604., 2995., 4395.,
       1395., 2953., 2400., 4663., 3597., 1590., 1330., 2198., 3855.,
       2771., 5998., 3598., 2495., 4806., 4163., 1597., 2596., 2773.,
       1985., 6592.])

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15503 non-null  object
 1   brand              15503 non-null  object
 2   model              15503 non-null  object
 3   vehicle_age        15503 non-null  int64
 4   km_driven          15503 non-null  object
 5   seller_type        15503 non-null  object
 6   fuel_type          15503 non-null  object
 7   transmission_type  15503 non-null  object
 8   mileage            14234 non-null  object
 9   engine             13651 non-null  float64
 10  max_power          14712 non-null  float64
 11  seats              15065 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.7+ MB

In [76]:
# For columns mileage, engine, and max_power — strip any unit strings (e.g. "kmpl", "CC", "bhp"), 
# convert to numeric using pd.to_numeric(..., errors='coerce'), and fill remaining nulls with each column's median.

df['mileage'].astype(str).str.strip().str.replace("kmpl","").str.replace("km","")
df['engine'].astype(str).str.strip().str.replace("CC","")
df['max_power'].astype(str).str.strip().str.replace("bhp","")

df['mileage'] = pd.to_numeric(df['mileage'], errors='coerce')
df['engine'] = pd.to_numeric(df['engine'], errors='coerce')
df['max_power'] = pd.to_numeric(df['max_power'], errors='coerce')

columns = ["mileage", "engine", "max_power"]
for col in columns:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)
    
    print(f"Filling '{col}' missing values with median: {median_value}")

Filling 'mileage' missing values with median: 19.67
Filling 'engine' missing values with median: 1248.0
Filling 'max_power' missing values with median: 88.5

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15503 non-null  object
 1   brand              15503 non-null  object
 2   model              15503 non-null  object
 3   vehicle_age        15503 non-null  int64
 4   km_driven          15503 non-null  object
 5   seller_type        15503 non-null  object
 6   fuel_type          15503 non-null  object
 7   transmission_type  15503 non-null  object
 8   mileage            15503 non-null  float64
 9   engine             15503 non-null  float64
 10  max_power          15503 non-null  float64
 11  seats              15065 non-null  float64
 12  selling_price      15503 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 1.7+ MB

In [78]:
print(f"Before cleaning: {df['km_driven'].unique()}\n")
df['km_driven'] = df['km_driven'].str.strip().str.replace('kms', '').str.replace('km', '').str.replace(',','').astype(int)
print(f"After cleaning: {df['km_driven'].unique()}")

Before cleaning: ['67647' '52000' '48959' ... '39337' '66850' '127731']

After cleaning: [ 67647  52000  48959 ...  39337  66850 127731]

In [79]:
# Remove rows where selling_price is 999999999 or below 10000.
before = len(df)
df = df[df['selling_price'] != 999999999]
df = df[df['selling_price'] >=10000]
after = len(df)
print(f"Removed rows: {before-after}")
print(f"Remaing rows: {after}")

Removed rows: 8
Remaing rows: 15495

In [80]:
# Drop all duplicate rows.
print("Before Drop DUplicates: ",df.duplicated().sum())
df = df.drop_duplicates()
print("Before Drop DUplicates:",df.duplicated().sum())

Before Drop DUplicates:  252
Before Drop DUplicates: 0

In [81]:
df.shape

(15243, 13)

Task 2 — Encode Categorical Features

Apply label encoding to transmission_type — map Manual → 0 and Automatic → 1.

Apply one-hot encoding to fuel_type and seller_type using pd.get_dummies() with drop_first=True.

Print the column list of the final DataFrame using df.columns.tolist().

In a markdown cell, answer: Why is drop_first=True used in one-hot encoding, and what does a row of all zeros in the new dummy columns represent?

In [82]:
# Apply label encoding to transmission_type — map Manual → 0 and Automatic → 1.
df['transmission_type'].value_counts()  # counting the transmission types

transmission_type
Manual       12084
Automatic     3159
Name: count, dtype: int64

In [83]:
# Now label encoding 
df['transmission_type'] = df['transmission_type'].map({"Manual":0, "Automatic":1})
print(df['transmission_type'].value_counts())

transmission_type
0    12084
1     3159
Name: count, dtype: int64

In [84]:
# shape of dataset
df.shape

(15243, 13)

In [85]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,0,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,0,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,0,19.67,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,0,15.40,2179.0,88.50,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,1,16.00,2179.0,140.00,7.0,1175000.0

# Apply one-hot encoding to fuel_type and seller_type using pd.get_dummies() with drop_first=True.

In [86]:
df['fuel_type'].unique()

array(['Diesel', 'CNG', 'Petrol', 'Petrol ', 'DIESEL', ' Petrol',
       'petrol ', 'PETROL', ' Diesel', 'diesel ', 'LPG', 'petrol',
       'diesel', 'Electric'], dtype=object)

In [87]:
# Removing spaces and chares in (fuel type) label
df['fuel_type'] = df['fuel_type'].astype(str).str.strip().str.title()
df['fuel_type'].unique()

array(['Diesel', 'Cng', 'Petrol', 'Lpg', 'Electric'], dtype=object)

In [88]:
# Removing Spaces,chars and Spellings. 
df['seller_type'].unique()

array(['Dealer', 'dealer', 'Individual', 'individual', 'DEALER',
       'Trustmark Dealer', 'Individul', 'Individuall', 'Delaer'],
      dtype=object)

In [89]:
spelling_corrections = {
    'Individuall' : 'Individual',
    'Individul' : 'Individual',
    'Trustmark Dealer': 'Trustmark Dealer',
    'Delaer': 'Dealer'
}
df['seller_type'] = df['seller_type'].astype(str).str.title().replace(spelling_corrections)

In [90]:
df['seller_type'].unique()

array(['Dealer', 'Individual', 'Trustmark Dealer'], dtype=object)

In [91]:
df['brand'].unique()

array(['Renault', 'Maruti', 'Honda', 'Mahindra', 'Hyundai', 'Ford',
       'Jeep', 'BMW', 'Jaguar', 'Skoda', 'Volkswagen', 'Tata',
       'Mercedes-Benz', 'Datsun', 'Audi', 'Tata ', 'Lexus', 'Hyundai ',
       'Toyota', 'Maruti ', 'Mahindra ', ' Maruti ', 'BMW ', 'Nissan',
       ' Mahindra', ' Mahindra ', ' Honda', ' Hyundai', ' Maruti',
       'Land Rover', ' Mercedes-Benz ', 'Mini', ' Honda ', ' Ford ',
       'Volvo', ' Toyota', 'Porsche', ' Tata ', ' Volkswagen ',
       ' Hyundai ', 'Kia', 'MG', ' BMW', 'Isuzu', ' Ford', 'Ford ',
       ' Renault ', 'Honda ', ' Tata', 'Mercedes-Benz ', 'Toyota ',
       ' Skoda ', ' Toyota ', ' Renault', 'Skoda ', ' Datsun',
       ' Volkswagen', ' Mercedes-AMG ', 'Audi ', 'Datsun ', ' Porsche',
       ' Datsun ', ' Audi', ' Skoda', ' Ferrari ', ' Mini ', 'Bentley',
       'Maserati', ' Audi ', 'Renault ', ' Nissan ', 'Volvo ', ' BMW ',
       'Force', 'Volkswagen ', ' Land Rover', 'ISUZU', ' MG ', ' ISUZU ',
       'Rolls-Royce'], dtype=object)

In [92]:
df['brand'] = df['brand'].astype(str).str.strip().str.title()

In [93]:
seats_mod = df['seats'].mode()[0]
df['seats'] = df['seats'].fillna(seats_mod)

In [94]:
df.shape

(15243, 13)

In [95]:
# Now Apply one-hot encoding to fuel_type and seller_type using pd.get_dummies() with drop_first=True.
df = pd.get_dummies(df, columns=['fuel_type', 'seller_type', 'brand'], drop_first=True)
df.head()

,car_name,model,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,selling_price,...,brand_Mini,brand_Nissan,brand_Porsche,brand_Renault,brand_Rolls-Royce,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,Renault Duster,Duster,7,67647,0,19.87,1461.0,83.80,5.0,575000.0,...,False,False,False,True,False,False,False,False,False,False
1,Maruti Wagon R,Wagon R,3,52000,0,33.54,998.0,67.04,5.0,435000.0,...,False,False,False,False,False,False,False,False,False,False
2,Honda City,City,3,48959,0,19.67,1497.0,117.60,5.0,875000.0,...,False,False,False,False,False,False,False,False,False,False
3,Mahindra Scorpio,Scorpio,6,82000,0,15.40,2179.0,88.50,8.0,925000.0,...,False,False,False,False,False,False,False,False,False,False
4,Mahindra XUV500,XUV500,4,34000,1,16.00,2179.0,140.00,7.0,1175000.0,...,False,False,False,False,False,False,False,False,False,False

In [96]:
df.shape

(15243, 46)

In [97]:
# Print the column list of the final DataFrame using df.columns.tolist().
df.columns.tolist()

['car_name',
 'model',
 'vehicle_age',
 'km_driven',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price',
 'fuel_type_Diesel',
 'fuel_type_Electric',
 'fuel_type_Lpg',
 'fuel_type_Petrol',
 'seller_type_Individual',
 'seller_type_Trustmark Dealer',
 'brand_Bentley',
 'brand_Bmw',
 'brand_Datsun',
 'brand_Ferrari',
 'brand_Force',
 'brand_Ford',
 'brand_Honda',
 'brand_Hyundai',
 'brand_Isuzu',
 'brand_Jaguar',
 'brand_Jeep',
 'brand_Kia',
 'brand_Land Rover',
 'brand_Lexus',
 'brand_Mahindra',
 'brand_Maruti',
 'brand_Maserati',
 'brand_Mercedes-Amg',
 'brand_Mercedes-Benz',
 'brand_Mg',
 'brand_Mini',
 'brand_Nissan',
 'brand_Porsche',
 'brand_Renault',
 'brand_Rolls-Royce',
 'brand_Skoda',
 'brand_Tata',
 'brand_Toyota',
 'brand_Volkswagen',
 'brand_Volvo']

Why is drop_first=True used in one-hot encoding, and what does a row of all zeros in the new dummy columns represent?

Ans:- The reason for dropping the first column in to prevent perfect multicollinearity. The multicollinearity occurs when one indepented variable in a regression model can be linarly predicted from high degree of accuracy.
when we using (drop first = true) the first category encountered is removed and become the reference category.

Task 3 — Split and Compute Baseline MAE

Define X (all columns except selling_price) and y (selling_price). Drop any remaining non-numeric columns from X.

Split into 80% train and 20% test using train_test_split with random_state=42.

Compute the baseline MAE: predict the mean of y_train for every row in the test set and calculate the MAE against y_test.

Print: "Baseline MAE: ₹X" rounded to the nearest rupee.

In [98]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [99]:
# Drop any remaining non-numeric columns from X.
print(df.columns)

Index(['car_name', 'model', 'vehicle_age', 'km_driven', 'transmission_type',
       'mileage', 'engine', 'max_power', 'seats', 'selling_price',
       'fuel_type_Diesel', 'fuel_type_Electric', 'fuel_type_Lpg',
       'fuel_type_Petrol', 'seller_type_Individual',
       'seller_type_Trustmark Dealer', 'brand_Bentley', 'brand_Bmw',
       'brand_Datsun', 'brand_Ferrari', 'brand_Force', 'brand_Ford',
       'brand_Honda', 'brand_Hyundai', 'brand_Isuzu', 'brand_Jaguar',
       'brand_Jeep', 'brand_Kia', 'brand_Land Rover', 'brand_Lexus',
       'brand_Mahindra', 'brand_Maruti', 'brand_Maserati',
       'brand_Mercedes-Amg', 'brand_Mercedes-Benz', 'brand_Mg', 'brand_Mini',
       'brand_Nissan', 'brand_Porsche', 'brand_Renault', 'brand_Rolls-Royce',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo'],
      dtype='object')

In [100]:
df = df.drop(columns=['car_name', 'model'])
df.head()

,vehicle_age,km_driven,transmission_type,mileage,engine,max_power,seats,selling_price,fuel_type_Diesel,fuel_type_Electric,...,brand_Mini,brand_Nissan,brand_Porsche,brand_Renault,brand_Rolls-Royce,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,7,67647,0,19.87,1461.0,83.80,5.0,575000.0,True,False,...,False,False,False,True,False,False,False,False,False,False
1,3,52000,0,33.54,998.0,67.04,5.0,435000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,48959,0,19.67,1497.0,117.60,5.0,875000.0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,6,82000,0,15.40,2179.0,88.50,8.0,925000.0,True,False,...,False,False,False,False,False,False,False,False,False,False
4,4,34000,1,16.00,2179.0,140.00,7.0,1175000.0,True,False,...,False,False,False,False,False,False,False,False,False,False

In [101]:
df.isna().sum()

vehicle_age                     0
km_driven                       0
transmission_type               0
mileage                         0
engine                          0
max_power                       0
seats                           0
selling_price                   0
fuel_type_Diesel                0
fuel_type_Electric              0
fuel_type_Lpg                   0
fuel_type_Petrol                0
seller_type_Individual          0
seller_type_Trustmark Dealer    0
brand_Bentley                   0
brand_Bmw                       0
brand_Datsun                    0
brand_Ferrari                   0
brand_Force                     0
brand_Ford                      0
brand_Honda                     0
brand_Hyundai                   0
brand_Isuzu                     0
brand_Jaguar                    0
brand_Jeep                      0
brand_Kia                       0
brand_Land Rover                0
brand_Lexus                     0
brand_Mahindra                  0
brand_Maruti                    0
brand_Maserati                  0
brand_Mercedes-Amg              0
brand_Mercedes-Benz             0
brand_Mg                        0
brand_Mini                      0
brand_Nissan                    0
brand_Porsche                   0
brand_Renault                   0
brand_Rolls-Royce               0
brand_Skoda                     0
brand_Tata                      0
brand_Toyota                    0
brand_Volkswagen                0
brand_Volvo                     0
dtype: int64

In [102]:
# Define X (all columns except selling_price) and y (selling_price). 

df.columns
x = df.drop(columns=['selling_price'])
y = df['selling_price']

In [103]:
# Split into 80% train and 20% test using train_test_split with random_state=42.
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.80, test_size=0.20, random_state=42)

In [111]:
# Compute the baseline MAE: predict the mean of y_train for every row in the test set and calculate the MAE against y_test.
model = LinearRegression()
model.fit(x_train,y_train)
y_train_pred = model.predict(x_train)
train_MAE = mean_absolute_error(y_train, y_train_pred)
print(f"Y train Predict value:{y_train_pred}\n")
print(f"Mean Absoluate Error value: {train_MAE}\n")

Avg_seals = df['selling_price'].mean()
df['base_pred'] = Avg_seals
base_MAE = mean_absolute_error(df['selling_price'], df['base_pred'])
print(f"Baseline MAE: ₹:- {base_MAE:.2f} ")

Y train Predict value:[ 455214.71532065 4079116.51294112 2011115.3925409  ... 1107515.98343751
  221746.60673053  368384.64759219]

Mean Absoluate Error value: 206614.597385519

Baseline MAE: ₹:- 454454.10